// Form Section Components - Export all
export { default as IdentificacionSection } from './IdentificacionSection'
export { default as SponsorSection } from './SponsorSection'
export { default as StakeholdersSection } from './StakeholdersSection'
export { default as ProblematicaSection } from './ProblematicaSection'
export { default as UrgenciaSection } from './UrgenciaSection'
export { default as SolucionSection } from './SolucionSection'
export { default as BeneficiosSection } from './BeneficiosSection'
export { default as DesempenoSection } from './DesempenoSection'
export { default as AdjuntosSection } from './AdjuntosSection'
export { default as DeclaracionSection } from './DeclaracionSection'
export { default as ReporteSection } from './ReporteSection'
export { default as CriticidadSection } from './CriticidadSection'
export { default as RazonamientoSection } from './RazonamientoSection'
export { default as ResponsablesSection } from './ResponsablesSection'
export { default as ConfirmacionCierreSection } from './ConfirmacionCierreSection'
